-- Supabase Migration Script
-- Run this SQL in your Supabase SQL Editor to create the summaries table

-- Create the summaries table
CREATE TABLE IF NOT EXISTS summaries (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  title TEXT NOT NULL,
  summary TEXT NOT NULL,
  keywords JSONB DEFAULT '[]'::jsonb,
  category TEXT NOT NULL,
  thread_id TEXT NOT NULL,
  channel_id TEXT NOT NULL,
  channel_name TEXT,
  thread_name TEXT,
  attachments JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_summaries_thread_id ON summaries(thread_id);
CREATE INDEX IF NOT EXISTS idx_summaries_channel_id ON summaries(channel_id);
CREATE INDEX IF NOT EXISTS idx_summaries_category ON summaries(category);
CREATE INDEX IF NOT EXISTS idx_summaries_created_at ON summaries(created_at DESC);

-- Create a full-text search index for title and summary
CREATE INDEX IF NOT EXISTS idx_summaries_search ON summaries USING gin(to_tsvector('english', title || ' ' || summary));

-- Enable Row Level Security (RLS) - adjust policies based on your needs
ALTER TABLE summaries ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows all operations (adjust based on your security needs)
-- For development, you can use this permissive policy:
CREATE POLICY "Allow all operations for authenticated users" ON summaries
  FOR ALL
  USING (true)
  WITH CHECK (true);

-- Or for public access (less secure, but simpler for development):
-- CREATE POLICY "Allow public access" ON summaries
--   FOR ALL
--   USING (true)
--   WITH CHECK (true);

-- Add comments for documentation
COMMENT ON TABLE summaries IS 'Stores Discord thread summaries generated by AI';
COMMENT ON COLUMN summaries.keywords IS 'Array of keywords extracted from the conversation';
COMMENT ON COLUMN summaries.attachments IS 'Array of attachment metadata from Discord messages';
